/***
 * This class has been created to select players
 * from their selected teams
 * Owner Name :- KRITIKA KUMARI
 * Date of Creation:- 17 September 2024
 */
package Week_3_Assignment;

public class PlayerList {
    public static String[] CSK = {"RITURAJ GAIKWAD","DEVON CONWAY","MS DHONI (c)","AJINKYA RAHANE","SHAIK RASHEED","SAMEER RIZVI","AVANISH RAO ARAVELLY",
            "SHARDUL THAKUR","DARYL MITCHELL","MATHEESHA PATHIRANA","RAVINDRA JADEJA","MOEEN ALI","MITCHELL SANTNER","SHIVAM DUBE",
            "NISHANT SINDHU","AJAY MANDAL","RACHIN RAVINDRA","SIMARJEET SINGH","TUSHAR DESHPANDE","RICHARD GLEESON","RAJVARDHAN HANGARGEKAR",
            "DEEPAK CHAHAR","MAHEESH THEEKSHANA","MUKESH CHOUDHARY","MUSTAFIZUR RAHMAN","PRASHANT SOLANKI"};

    public static String[] DC = {"RISHABH PANT (c)","DAVID WARNER","PRITHVI SHAW","YASH DHULL","SHAI HOPE","SWASTIK CHHIKARA","ABHISHEK POREL","RICKY BHUI",
            "KUMAR KUSHAGRA","TRISTAN STUBBS","AXAR PATEL","LALIT YADAV","MITCHELL MARSH","GULBADIN NAIB","SUMIT KUMAR","PRAVIN DUBEY",
            "VICKY OSTWAL","ANRICH NORTJE","KULDEEP YADAV","KHALEEL AHMED","ISHANT SHARMA","JHYE RICHARDSON","LIZAAD WILLIAMS","MUKESH KUMAR","RASIKH DAR"};

    public static String[] MI = {"ROHIT SHARMA","DEWALD BREVIS","SURYAKUMAR YADAV","ISHAN KISHAN","HARVIK DESAI","N. TILAK VERMA","TIM DAVID","VISHNU VINOD",
            "HARDIK PANDYA (c)","ARJUN TENDULKAR","MOHAMMAD NABI","ROMARIO SHEPHERD","SHAMS MULANI","NEHAL WADHERA","GERALD COETZEE","ANSHUL KAMBOJ",
            "NAMAN DHIR","SHIVALIK SHARMA","KWENA MAPHAKA","JASPRIT BUMRAH","PIYUSH CHAWLA","KUMAR KARTIKEYA SINGH","AKASH MADHWAL","LUKE WOOD",
            "SHREYAS GOPAL","NUWAN THUSHARA"};

    public static String[] LSG = {"KL RAHUL (c)","DEVDUTT PADIKKAL","QUINTON DE KOCK","NICHOLAS POORAN","ASHTON TURNER","AYUSH BADONI","DEEPAK HOODA","KRISHNAPPA GOWTHAM",
            "KRUNAL PANDYA","KYLE MAYERS","MARCUS STOINIS","MOHD. ARSHAD KHAN","PRERAK MANKAD","YUDHVIR SINGH","ARSHIN KULKARNI","SHIVAM MAVI",
            "SHAMAR JOSEPH","MATT HENRY","MAYANK YADAV","MOHSIN KHAN","RAVI BISHNOI", "YASH THAKUR","AMIT MISHRA","NAVEEN UL HAQ","M SIDDHARTH"};

    public static String[] KKR = {"SHREYAS IYER (c)","RINKU SINGH","RAHMANULLAH GURBAZ","NITISH RANA","SHERFANE RUTHERFORD","PHIL SALT","K.S BHARAT","MANISH PANDEY",
            "ANGKRISH RAGHUVANSHI","ANKUL ROY","RAMANDEEP SINGH","ANDRE RUSSELL","VENKATESH IYER","SUYASH SHARMA","DUSHMANTHA CHAMEERA","SAKIB HUSSAIN",
            "HARSHIT RANA","SUNIL NARAINE","VAIBHAV ARORA","VARUN CHAKARAVARTHY","MITCHELL STARC","CHETAN SAKARIYA"};

    public static String[] RCB = {"FAF DU PLESSIS (c)","RAJAT PATIDAR","VIRAT KOHLI","ANUJ RAWAT","DINESH KARTHIK","SUYASH S PRABHUDESSAI","WILL JACKS","SAURAV CHAUHAN",
            "GLENN MAXWELL","MAHIPAL LOMROR","KARN SHARMA","CAMERON GREEN","SWAPNIL SINGH","MAYANK DAGAR","MANOJ BHANDAGE","AKASH DEEP","ALZARRI JOSEPH",
            "LOCKIE FERGUSON","MOHAMMED SIRAJ","YASH DAYAL","TOM CURRAN","REECE TOPLEY","HIMANSHU SHARMA","RAJAN KUMAR","VYSHAK VIJAY KUMAR"};

    public static String[] SRH = {"ABDUL SAMAD","AIDEN MARKRAM","RAHUL TRIPATHI","GLENN PHILLIPS","MAYANK AGARWAL","HEINRICH KLAASEN","ANMOLPREET SINGH","UPENDRA SINGH YADAV",
            "TRAVIS HEAD","ABHISHEK SHARMA","MARCO JANSEN","WASHINGTON SUNDAR","SANVIR SINGH","NITISH KUMAR REDDY","WANINDU HASARANGA","PAT CUMMINS (c)",
            "AKASH SINGH","SHAHBAZ AHMAD","BHUVNESHWAR KUMAR","FAZALHAQ FAROOQI","JAYDEV UNADKAT","T NATARAJAN","UMRAN MALIK","MAYANK MARKANDE",
            "JHATHAVEDH SUBRAMANYAN","VIJAYAKANTH VIYASKANTH"};

    public static String[] PK = {"SHIKHAR DHAWAN (c)","JITESH SHARMA","JONNY BAIRSTOW","PRABHSIMRAN SINGH","LIAM LIVINGSTONE","HARPREET BHATIA","RILEE ROSSOUW","SHASHANK SINGH",
            "CHRIS WOAKES","VISHWANATH PRATAP SINGH","ASHUTOSH SHARMA","TANAY THYAGARAJANN","ATHARVA TAIDE","RISHI DHAWAN","SAM CURRAN","SIKANDAR RAZA","SHIVAM SINGH",
            "PRINCE CHOUDHARY","HARPREET BRAR","ARSHDEEP SINGH","KAGISO RABADA","NATHAN ELLIS","RAHUL CHAHAR","VIDWATH KAVERAPPA","HARSHAL PATEL"};
    public static String[] GT = {"SHUBMAN GILL (c)","DAVID MILLER","MATTHEW WADE","WRIDDHIMAN SAHA","BR SHARATH","KANE WILLIAMSON","ABHINAV MANOHAR","B. SAI SUDHARSAN",
            "DARSHAN NALKANDE","VIJAY SHANKAR","AZMATULLAH OMARZAI","SHAHRUKH KHAN","SANDEEP WARRIER","JAYANT YADAV","RAHUL TEWATIA","MOHAMMAD SHAMI","KARTIK TYAGI",
            "SUSHANT MISHRA","SPENCER JOHNSON","NOOR AHMAD","SAI KISHORE","UMESH YADAV","RASHID KHAN","JOSHUA LITTLE","MOHIT SHARMA","MANAV SUTHAR"};

    public static String[] RR = {"SANJU SAMSON (c)","JOS BUTTLER","SHIMRON HETMYER","YASHASVI JAISWAL","DHRUV JUREL","RIYAN PARAG","KUNAL RATHORE","DONOVAN FERREIRA",
            "ROVMAN POWELL","SHUBHMAN DUBEY","TOM KOHLER-CADMORE","RAVICHANDRAN ASHWIN","TANUSH KOTIAN","ABID MUSHTAQ","AVESH KHAN","KULDEEP SEN",
            "KESHAV MAHARAJ","SANDEEP SHARMA","TRENT BOULT","YUZVENDRA CHAHAL","NANDRE BURGER"};

    // To input players from the team list
    // Return type - String
    // Parameters - Integer, String
    public static String Team(int index, String Team){
        String string = "";
        return switch (Team) {
            case "CSK", "csk" -> CSK[index];
            case "RCB", "rcb" -> RCB[index];
            case "GT", "gt" -> GT[index];
            case "LSG", "lsg" -> LSG[index];
            case "MI", "mi" -> MI[index];
            case "RR", "rr" -> RR[index];
            case "DC", "dc" -> DC[index];
            case "PK", "pk" -> PK[index];
            case "KKR", "kkr" -> KKR[index];
            case "SRH", "srh" -> SRH[index];
            default -> string;
        };
    }
}